### ISSUE TITLE
Running out of gas

### ISSUE THREAD

**Issue by ethernomad** [nexusdev/dapple-test#3] opened 2016-10-05 18:37 UTC
I'm running out of gas when running tests. `Error: Contract deployment error: Error: VM Exception while executing transaction: out of gas`

I increased the limit in vmtest.js, but now I get `Error: Contract deployment error: tx has a higher gas limit than the block`

How can I increase the block gas limit?

**Comment by ethernomad** [comment] 2016-10-05 18:45
Here's the test file: https://github.com/link-blockchain/blobstore/blob/master/blobstore_test.sol

If I add any more test methods I hit the gas limit.

**Comment by mhhf** [comment] 2016-10-07 10:51
can't reproduce with dapple 0.8.3. Which version are you using?
also can you print out the output of `dapple status` to help me understand your environment

**Comment by ethernomad** [comment] 2016-10-07 13:12
Running Dapple from latest `master`:

```
dapple --version
0.8.3
```

Here is the output from `dapple status`:

```
Chain: develop

fork root: undefined
height: +NaN (dev)

default account:
0x0000000000000000000000000000000000000000

faked accounts:
0x0000000000000000000000000000000000000000

Context:



```

**Comment by ethernomad** [comment] 2016-10-07 13:15
Add one more test method to BlobStoreTest and it will run out of gas:

```
BlobStoreTest
  Error: VM Exception while executing transaction: out of gas
Failing Tests
  BlobStoreTest: Deployment failure

Summary
  Failed 1 out of 1 tests.
```

**Comment by mhhf** [comment] 2016-10-08 08:23
Addressing this issue i've added travis based dapple test to your repo which also can't reproduce the out-of-gas error: https://github.com/link-blockchain/blobstore/pull/2
see here: https://travis-ci.org/nexusdev/blobstore

Maybe there is something wrong with your environment -- try to remove `.dapple` folder in your project directory and run the tests again...

**Comment by ethernomad** [comment] 2016-10-12 08:56
Thanks for taking a look at this!

I merged your pull request and made a new branch with an extra test that is enough to trigger the problem: https://github.com/link-blockchain/blobstore/tree/testfail

Can you try it again on that branch?

I updated to latest Dapple and removed .dapple, but it didn't make any difference.

**Comment by mhhf** [comment] 2016-10-12 10:50
Cannot reproduce on my machine (OS X 10.11.6) but reproduce it on Ubuntu! Can you confirm you work on Linux/Ubuntu as well?
Will debug this down and fix this bug asap.

**Comment by ethernomad** [comment] 2016-10-12 10:51
Cool! Yes I am on latest Ubuntu.

**Comment by mhhf** [comment] 2016-10-12 12:19
Writeup for future work:
it is not a dapple problem but deep deep down in ethereumjs-vm
the problem is how an os stores buffers
if a buffer is 20 byte long, but is prefixed with 00 an internal optimizer or a serealizer and deserializer cuts of this prefix
the problem was that a contract was deployed with an 00 prefixed address: `0x00b68db15676a4024a0b2cfe93c41c10c2323c44`
 durch 
after some vm steps the address got "optimized" to `0xb68db15676a4024a0b2cfe93c41c10c2323c44`
and thus, after code lookup in the merkle-trie no code could be found which leads to an error

TODO: update ethereumjs-vm, if bug persists, find precisely where this happens and discuss possible solutions with ethereumjs guys

**Comment by mhhf** [comment] 2016-11-08 20:17
Fixed in ethereumjs-vm and included in this project

**Closed as completed by mhhf** 2016-11-08 20:17 UTC
Labels: bug
