### ISSUE TITLE
Warning: Source file does not specify required compiler version!

### ISSUE THREAD

**Issue by ethernomad** [nexusdev/dapple-test#1] opened 2016-10-05 13:38 UTC
```
Testing...
<stdin>:2:1: Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.4.2;".

^
```

I don't know why this warning appears, because all the contracts and test.sol declare the required compiler version.

**Comment by apmilen** [comment] 2016-10-06 05:48
does the compiler say which file is causing this warning?

**Comment by mhhf** [comment] 2016-10-07 11:07
This was caused by the way we test wether the native solc compiler is available. Is solved in then next version and will be included in dapple 0.8.4 today or tomorrow.

**Comment by mhhf** [comment] 2016-11-11 16:16
Closing as this is resolved.

**Closed as completed by mhhf** 2016-11-11 16:16 UTC
